### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SipeP** [NinerBull/AccWideUILayoutSelection#1]
Hi,
Whenever i login i get this error:

> 5x ...ccWideUILayoutSelection/AccWideUILayoutSelection.lua:715: attempt to index local 'classColorString' (a nil value)
> [string "@AccWideUILayoutSelection/AccWideUILayoutSelection.lua"]:715: in function `InitializeOptions'
> [string "@AccWideUILayoutSelection/AccWideUILayoutSelection.lua"]:354: in function <...ccWideUILayoutSelection/AccWideUILayoutSelection.lua:165>
> [string "=[C]"]: in function `NotifySettingsLoaded'
> [string "@SharedXML/Settings/Blizzard_SettingsRegistrar.lua"]:19: in function <...ce/SharedXML/Settings/Blizzard_SettingsRegistrar.lua:11>
> [string "@SharedXML/EventUtil.lua"]:21: in function <SharedXML/EventUtil.lua:15>
> [string "=[C]"]: ?
> [string "@SharedXML/CallbackRegistry.lua"]:178: in function <SharedXML/CallbackRegistry.lua:177>
> [string "=[C]"]: ?
> [string "@SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
> [string "@SharedXML/GlobalCallbackRegistry.lua"]:9: in function <SharedXML/GlobalCallbackRegistry.lua:8>
> 
> Locals:
> self = nil
> thisPointX = 16
> thisPointY = -375
> title = ARTWORK {
>  0 = <userdata>
> }
> title2 = ARTWORK {
>  0 = <userdata>
> }
> b1 = Button {
>  SetTextToFit = <function> defined @SharedXML/SecureUIPanelTemplates.lua:244
>  Right = Texture {
>  }
>  Left = Texture {
>  }
>  fitTextWidthPadding = 40
>  FitToText = <function> defined @SharedXML/SecureUIPanelTemplates.lua:249
>  Text = TopText {
>  }
>  0 = <userdata>
>  Middle = Texture {
>  }
>  fitTextCanWidthDecrease = true
> }
> chkEnableDefault = CheckButton {
>  0 = <userdata>
>  Text = TopText {
>  }
>  text = TopText {
>  }
> }
> chkShowText = CheckButton {
>  0 = <userdata>
>  Text = TopText {
>  }
>  text = TopText {
>  }
> }
> titleSA = ARTWORK {
>  0 = <userdata>
> }
> titleSA2 = ARTWORK {
>  0 = <userdata>
> }
> chkSaveEditModeLayout = CheckButton {
>  0 = <userdata>
>  Text = TopText {
>  }
>  text = TopText {
>  }
> }
> chkSaveActionBar = CheckButton {
>  0 = <userdata>
>  Text = TopText {
>  }
>  text = TopText {
>  }
> }
> chkSaveNameplates = CheckButton {
>  0 = <userdata>
>  Text = TopText {
>  }
>  text = TopText {
>  }
> }
> chkSaveRaidFrames = CheckButton {
>  0 = <userdata>
>  Text = TopText {
>  }
>  text = TopText {
>  }
> }
> chkSaveArenaFrames = CheckButton {
>  0 = <userdata>
>  Text = TopText {
>  }
>  text = TopText {
>  }
> }
> classColorString = nil
> titleCS = ARTWORK {
>  0 = <userdata>
> }
> (*temporary) = <function> defined =[C]:-1
> (*temporary) = ARTWORK {
>  0 = <userdata>
> }
> (*temporary) = "TOPLEFT"
> (*temporary) = nil
> (*temporary) = -375
> (*temporary) = <userdata>
> (*temporary) = nil
> (*temporary) = <userdata>
> (*temporary) = <table> {
>  GetID = <function> defined @SharedXML/Settings/Blizzard_Category.lua:13
>  SetCategorySet = <function> defined @SharedXML/Settings/Blizzard_Category.lua:53
>  order = 122
>  HasSubcategories = <function> defined @SharedXML/Settings/Blizzard_Category.lua:72
>  CreateSubcategory = <function> defined @SharedXML/Settings/Blizzard_Category.lua:76
>  SetCategoryTutorialInfo = <function> defined @SharedXML/Settings/Blizzard_Category.lua:83
>  HasParentCategory = <function> defined @SharedXML/Settings/Blizzard_Category.lua:49
>  SetOrder = <function> defined @SharedXML/Settings/Blizzard_Category.lua:29
>  ID = "Account Wide Interface Option Settings"
>  Init = <function> defined @SharedXML/Settings/Blizzard_Category.lua:6
>  GetParentCategory = <function> defined @SharedXML/Settings/Blizzard_Category.lua:41
>  categorySet = 2
>  GetName = <function> defined @SharedXML/Settings/Blizzard_Category.lua:17
>  name = "Account Wide Interface Option Settings"
>  subcategories = <table> {
>  }
>  GetOrder = <function> defined @SharedXML/Settings/Blizzard_Category.lua:25
>  SetName = <function> defined @SharedXML/Settings/Blizzard_Category.lua:21
>  SetParentCategory = <function> defined @SharedXML/Settings/Blizzard_Category.lua:45
>  GetCategoryTutorialInfo = <function> defined @SharedXML/Settings/Blizzard_Category.lua:90
>  GetQualifiedName = <function> defined @SharedXML/Settings/Blizzard_Category.lua:33
>  GetSubcategories = <function> defined @SharedXML/Settings/Blizzard_Category.lua:68
>  GetCategorySet = <function> defined @SharedXML/Settings/Blizzard_Category.lua:57
> }
> (*temporary) = nil
> (*temporary) = true
> (*temporary) = "attempt to index local 'classColorString' (a nil value)"

**Comment by NinerBull** [comment]
This should hopefully be fixed now in #https://github.com/NinerBull/AccWideUILayoutSelection/releases/tag/v1.1.2 - thanks for the report!
