### ISSUE TITLE
Getting Error in Dawnbreaker 

### ISSUE THREAD

**Issue by davpheol** [NinerBull/AccWideUILayoutSelection#4]
Hello,

Im getting an Error in Dawnbreaker during the first phase of the Rasha'nan boss once i pick up the exploding barrels. The extra action buttons doesnt appear so the whole mechanic cant be done by me. I assume its the same for every instance where the extra action button is used but havent tested that yet. Tested it once after the first boss in Rookery but no error.

```
2x [ADDON_ACTION_BLOCKED] AddOn 'AccWideUILayoutSelection' tried to call the protected function 'ExtraActionBarFrame:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Show'
[string "@Blizzard_UIPanels_Game/Mainline/ExtraAbilityContainer.lua"]:49: in function `AddFrame'
[string "@Blizzard_ActionBar/Mainline/ExtraActionBar.lua"]:17: in function `ExtraActionBar_Update'
[string "@Blizzard_ActionBarController/Mainline/ActionBarController.lua"]:92: in function <...ActionBarController/Mainline/ActionBarController.lua:55>

Locals:
Skipped (In Encounter)
```
![grafik](https://github.com/user-attachments/assets/f72dca30-2d5f-4ec8-8d14-365c70aa59be)

**Comment by davpheol** [comment]
getting also an error with the follower dungeon button (giving the npcs the lead) but the button itself is there unlike above with the last boss
```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'AccWideUILayoutSelection' tried to call the protected function 'CastSpellByID()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `CastSpellByID'
[string "@Blizzard_ZoneAbility/ZoneAbility.lua"]:265: in function <Blizzard_ZoneAbility/ZoneAbility.lua:263>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}
```

**Comment by NinerBull** [comment]
Hey there,
I've been trying to figure this out, it's somewhat random when it happens. But I can narrow it down to one thing - the loading of visible Action Bars.

As a temporary workaround, you can disable the Action Bars option in this addon and see if it helps. I'll continue looking for a proper solution though!

**Comment by NinerBull** [comment]
Hello again,
I just pushed out a new version that should hopefully fix the problem.
Could you please update to the [latest version](https://github.com/NinerBull/AccWideUILayoutSelection/releases/latest) and see if it fixes it for you?
Thanks!

**Comment by davpheol** [comment]
updated and did a few test runs. No Error everytime so it looks like its fixed. Thank you for the update and the amazing addon !
